{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wunused-imports -Werror=incomplete-patterns #-}

module Main (main) where

import Acac (FetchWindow (..), ParsedArgs (..), Submission, aggregate, buildSubmissionsUrl, noAcMessage, parseArgs, renderTable, retryWindow, splitIntoWeeks, windowFromSecond)
import Control.Concurrent (threadDelay)
import Data.Aeson (eitherDecode)
import Data.Text (Text)
import Data.Time.Clock.POSIX (getPOSIXTime)
import Network.HTTP.Simple
  ( getResponseBody,
    getResponseStatusCode,
    httpLBS,
    parseRequest,
    setRequestHeader,
  )
import System.Environment (getArgs)
import System.Exit (die)

-- リクエスト間の sleep。API への礼儀で 1 秒超にする。
sleepBetweenRequests :: IO ()
sleepBetweenRequests = threadDelay 1100000

main :: IO ()
main = do
  args <- getArgs
  case parseArgs args of
    Left err -> die err
    Right ShowHelp -> putStr usageText
    Right (Run username) -> do
      now <- round <$> getPOSIXTime
      submissions <- fetchRecent username now
      let acRecords = aggregate submissions
      if null acRecords
        then putStrLn $ noAcMessage username
        else do
          putStr creditBanner
          putStrLn $ renderTable $ splitIntoWeeks acRecords

-- | `--help` で表示する usage テキスト。
usageText :: String
usageText =
  unlines
    [ "usage: acac <atcoder-username>",
      "",
      "Show recent AtCoder AC history as a weekly table.",
      "",
      "options:",
      "  --help, -h  show this help message and exit"
    ]

-- | 表の前に出力する、生成元を示すクレジット文字列(末尾の空行で表と区切る)。
creditBanner :: String
creditBanner =
  unlines
    [ "Generated by acac-cli",
      "https://github.com/RyosukeDTomita/acac-cli",
      ""
    ]

-- | 直近の提出を取得する。
-- まず4週間ぶんを1リクエストで試し、満杯(=1アクセスに収まらない)なら
-- 直近1週間に絞って取り直す(最低1週間は表示する)。
fetchRecent :: Text -> Int -> IO [Submission]
fetchRecent username now = do
  batch <- fetchPage username (windowFromSecond WideWindow now)
  case retryWindow batch of
    Nothing -> pure batch
    Just window -> do
      sleepBetweenRequests
      fetchPage username (windowFromSecond window now)

-- | 1 リクエストぶんの提出を取得する。
-- Cloudflare 対策で Accept-Encoding: gzip を付ける(http-conduit が自動で解凍する)。
fetchPage :: Text -> Int -> IO [Submission]
fetchPage username fromSecond = do
  request <-
    setRequestHeader "Accept-Encoding" ["gzip"]
      <$> parseRequest (buildSubmissionsUrl username fromSecond)
  response <- httpLBS request
  let status = getResponseStatusCode response
  if status /= 200
    then die ("API returned HTTP " ++ show status)
    else case eitherDecode (getResponseBody response) of
      Left err -> die ("failed to parse API response: " ++ err)
      Right submissions -> pure submissions
